//
// Copyright (c) 2020 Ankur Srivastava
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

package app

import (
	_ "github.com/ansrivas/fiber-pongo2-pkger/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/ansrivas/fiber-pongo2-pkger/pkg/routers"
	swagger "github.com/arsmn/fiber-swagger"
	"github.com/gofiber/fiber"
)

// RegisterRoutes registers all the routes associated with this application.
func (app *App) RegisterRoutes(routes *routers.Routers) {

	app.Server.Get("/", func(c *fiber.Ctx) {
		c.Redirect(prepareRoutes(app.ProxyURL, "/ui/index.html"), fiber.StatusTemporaryRedirect)
	})
	app.Server.Use("/swagger", swagger.Handler)            // default
	app.Server.Use("/swagger", swagger.New(swagger.Config{ // custom
		URL:         "http://example.com/doc.json",
		DeepLinking: false,
	}))

	app.Server.Get(prepareRoutes(app.ProxyURL, "/healthz"), routes.GetHandlerHealthz)

	uiGroup := app.Server.Group("/ui")
	{
		uiGroup.Get(prepareRoutes(app.ProxyURL, "/index.html"), routes.GetIndexHTML)
	}
}
