//
// Copyright (c) 2020 Ankur Srivastava
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

package app

import (
	_ "github.com/ansrivas/fiber-pongo2-pkger/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/ansrivas/fiber-pongo2-pkger/pkg/routers"
	"github.com/ansrivas/fiberprometheus/v2"
	swagger "github.com/arsmn/fiber-swagger/v2"
	"github.com/gofiber/fiber/v2"
)

// RegisterRoutes registers all the routes associated with this application.
func (app *App) RegisterRoutes(routes *routers.Routers) {

	// This here will appear as a label, one can also use
	// fiberprometheus.NewWith(servicename, namespace, subsystem )
	prometheus := fiberprometheus.New("template-app")
	prometheus.RegisterAt(app.Server, "/metrics")
	app.Server.Use(prometheus.Middleware)

	// Register swagger URL
	app.Server.Use("/swagger", swagger.Handler) // default
	// app.Server.Use("/swagger", swagger.New(swagger.Config{ // custom
	// 	URL:         "http://example.com/doc.json",
	// 	DeepLinking: false,
	// }))

	app.Server.Get("/", func(c *fiber.Ctx) error {
		return c.Redirect(prepareRoutes(app.ProxyURL, "/ui/index.html"), fiber.StatusTemporaryRedirect)
	})

	app.Server.Get(prepareRoutes(app.ProxyURL, "/healthz"), routes.GetHandlerHealthz)

	uiGroup := app.Server.Group(prepareRoutes(app.ProxyURL, "/ui"))
	{
		// Note we are not passing prepareRoutes as we prefixed the proxy earlier
		uiGroup.Get("/index.html", routes.GetIndexHTML)
	}
}
